[package]
name = "Rusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
httparse = "1.7.1"
try-catch = "0.2.2"
dirs = "4.0.0"